//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitoring.JCDecauxAdminService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdminStats", Namespace="http://schemas.datacontract.org/2004/07/JCDecauxLibrary")]
    [System.SerializableAttribute()]
    public partial class AdminStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NbRequestsOnCacheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Monitoring.JCDecauxAdminService.Request[] RequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeCachedSecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeForRequestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbRequests {
            get {
                return this.NbRequestsField;
            }
            set {
                if ((this.NbRequestsField.Equals(value) != true)) {
                    this.NbRequestsField = value;
                    this.RaisePropertyChanged("NbRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbRequestsOnCache {
            get {
                return this.NbRequestsOnCacheField;
            }
            set {
                if ((this.NbRequestsOnCacheField.Equals(value) != true)) {
                    this.NbRequestsOnCacheField = value;
                    this.RaisePropertyChanged("NbRequestsOnCache");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Monitoring.JCDecauxAdminService.Request[] Requests {
            get {
                return this.RequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestsField, value) != true)) {
                    this.RequestsField = value;
                    this.RaisePropertyChanged("Requests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeCachedSec {
            get {
                return this.TimeCachedSecField;
            }
            set {
                if ((this.TimeCachedSecField.Equals(value) != true)) {
                    this.TimeCachedSecField = value;
                    this.RaisePropertyChanged("TimeCachedSec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeForRequests {
            get {
                return this.TimeForRequestsField;
            }
            set {
                if ((this.TimeForRequestsField.Equals(value) != true)) {
                    this.TimeForRequestsField = value;
                    this.RaisePropertyChanged("TimeForRequests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/JCDecauxLibrary")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCachedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCached {
            get {
                return this.IsCachedField;
            }
            set {
                if ((this.IsCachedField.Equals(value) != true)) {
                    this.IsCachedField = value;
                    this.RaisePropertyChanged("IsCached");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecauxAdminService.IJCDecauxAdmin")]
    public interface IJCDecauxAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/GetStats", ReplyAction="http://tempuri.org/IJCDecauxAdmin/GetStatsResponse")]
        Monitoring.JCDecauxAdminService.AdminStats GetStats();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/GetStats", ReplyAction="http://tempuri.org/IJCDecauxAdmin/GetStatsResponse")]
        System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> GetStatsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/SetTimeCache", ReplyAction="http://tempuri.org/IJCDecauxAdmin/SetTimeCacheResponse")]
        Monitoring.JCDecauxAdminService.AdminStats SetTimeCache(int timeCache);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/SetTimeCache", ReplyAction="http://tempuri.org/IJCDecauxAdmin/SetTimeCacheResponse")]
        System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> SetTimeCacheAsync(int timeCache);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/SetTimeForRequests", ReplyAction="http://tempuri.org/IJCDecauxAdmin/SetTimeForRequestsResponse")]
        Monitoring.JCDecauxAdminService.AdminStats SetTimeForRequests(int timeForRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxAdmin/SetTimeForRequests", ReplyAction="http://tempuri.org/IJCDecauxAdmin/SetTimeForRequestsResponse")]
        System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> SetTimeForRequestsAsync(int timeForRequests);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxAdminChannel : Monitoring.JCDecauxAdminService.IJCDecauxAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxAdminClient : System.ServiceModel.ClientBase<Monitoring.JCDecauxAdminService.IJCDecauxAdmin>, Monitoring.JCDecauxAdminService.IJCDecauxAdmin {
        
        public JCDecauxAdminClient() {
        }
        
        public JCDecauxAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Monitoring.JCDecauxAdminService.AdminStats GetStats() {
            return base.Channel.GetStats();
        }
        
        public System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> GetStatsAsync() {
            return base.Channel.GetStatsAsync();
        }
        
        public Monitoring.JCDecauxAdminService.AdminStats SetTimeCache(int timeCache) {
            return base.Channel.SetTimeCache(timeCache);
        }
        
        public System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> SetTimeCacheAsync(int timeCache) {
            return base.Channel.SetTimeCacheAsync(timeCache);
        }
        
        public Monitoring.JCDecauxAdminService.AdminStats SetTimeForRequests(int timeForRequests) {
            return base.Channel.SetTimeForRequests(timeForRequests);
        }
        
        public System.Threading.Tasks.Task<Monitoring.JCDecauxAdminService.AdminStats> SetTimeForRequestsAsync(int timeForRequests) {
            return base.Channel.SetTimeForRequestsAsync(timeForRequests);
        }
    }
}
