//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milleret.JCDecauxLibraryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecauxLibraryService.IJCDecauxOperations")]
    public interface IJCDecauxOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetTowns", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetTownsResponse")]
        JCDecauxLibrary.Town[] GetTowns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetTowns", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetTownsResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Town[]> GetTownsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetStationsFromTown", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetStationsFromTownResponse")]
        JCDecauxLibrary.Station[] GetStationsFromTown(string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetStationsFromTown", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetStationsFromTownResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Station[]> GetStationsFromTownAsync(string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetAvailableVelib", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetAvailableVelibResponse")]
        JCDecauxLibrary.Station GetAvailableVelib(string station, string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetAvailableVelib", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetAvailableVelibResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Station> GetAvailableVelibAsync(string station, string town);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxOperationsChannel : Milleret.JCDecauxLibraryService.IJCDecauxOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxOperationsClient : System.ServiceModel.ClientBase<Milleret.JCDecauxLibraryService.IJCDecauxOperations>, Milleret.JCDecauxLibraryService.IJCDecauxOperations {
        
        public JCDecauxOperationsClient() {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JCDecauxLibrary.Town[] GetTowns() {
            return base.Channel.GetTowns();
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Town[]> GetTownsAsync() {
            return base.Channel.GetTownsAsync();
        }
        
        public JCDecauxLibrary.Station[] GetStationsFromTown(string town) {
            return base.Channel.GetStationsFromTown(town);
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Station[]> GetStationsFromTownAsync(string town) {
            return base.Channel.GetStationsFromTownAsync(town);
        }
        
        public JCDecauxLibrary.Station GetAvailableVelib(string station, string town) {
            return base.Channel.GetAvailableVelib(station, town);
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Station> GetAvailableVelibAsync(string station, string town) {
            return base.Channel.GetAvailableVelibAsync(station, town);
        }
    }
}
