//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCDecauxLibrary {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCDecauxLibrary.IJCDecauxOperations")]
    public interface IJCDecauxOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetTowns", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetTownsResponse")]
        JCDecauxLibrary.Town[] GetTowns(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetTowns", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetTownsResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Town[]> GetTownsAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetStationsFromTown", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetStationsFromTownResponse")]
        JCDecauxLibrary.Station[] GetStationsFromTown(string key, string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetStationsFromTown", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetStationsFromTownResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Station[]> GetStationsFromTownAsync(string key, string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetAvailableVelib", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetAvailableVelibResponse")]
        JCDecauxLibrary.Station GetAvailableVelib(string key, string station, string town);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCDecauxOperations/GetAvailableVelib", ReplyAction="http://tempuri.org/IJCDecauxOperations/GetAvailableVelibResponse")]
        System.Threading.Tasks.Task<JCDecauxLibrary.Station> GetAvailableVelibAsync(string key, string station, string town);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCDecauxOperationsChannel : JCDecauxLibrary.IJCDecauxOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCDecauxOperationsClient : System.ServiceModel.ClientBase<JCDecauxLibrary.IJCDecauxOperations>, JCDecauxLibrary.IJCDecauxOperations {
        
        public JCDecauxOperationsClient() {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCDecauxOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JCDecauxLibrary.Town[] GetTowns(string key) {
            return base.Channel.GetTowns(key);
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Town[]> GetTownsAsync(string key) {
            return base.Channel.GetTownsAsync(key);
        }
        
        public JCDecauxLibrary.Station[] GetStationsFromTown(string key, string town) {
            return base.Channel.GetStationsFromTown(key, town);
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Station[]> GetStationsFromTownAsync(string key, string town) {
            return base.Channel.GetStationsFromTownAsync(key, town);
        }
        
        public JCDecauxLibrary.Station GetAvailableVelib(string key, string station, string town) {
            return base.Channel.GetAvailableVelib(key, station, town);
        }
        
        public System.Threading.Tasks.Task<JCDecauxLibrary.Station> GetAvailableVelibAsync(string key, string station, string town) {
            return base.Channel.GetAvailableVelibAsync(key, station, town);
        }
    }
}
